#!/bin/sh
# Installs the Nexthink Collector from previously cached installation files
#   Version: 1.0
#   Author: Ryan Powell
#   Reference: https://github.com/rypowell1988/mac-management/blob/master/Install%20Nexthink%20Collector
#   Note: This script uses:
#            Parameter 4 in the JSS to define the Nexthink Server Name       
#            Parameter 5 in the JSS to define the Nexthink Server Port


# CHECK PARAMETERS HAVE BEEN PASSED
   if [[ $4 == "" ]]; then
      exit 1
   fi
   if [[ $5 == "" ]]; then
      exit 1
   fi


#  SOME VARIABLES
   cachedInstaller=/private/var/tmp/Nexthink


# CHECK IF THE INSTALLER HAS BEEN CACHED
   if [[ ! -d $cachedInstaller ]]; then
      echo "Nexthink installer not found at $cachedInstaller"
      exit 1
   fi


# EXECUTE THE INSTALLER
   echo "Executing cached installer"
   cd "$cachedInstaller/csi.app/Contents/MacOS"
   sudo ./csi -address "$4" -port "$5"
   # Did the install work?
   respCode=$?
   if [[ $respCode > 0 ]]; then
      # Non 0 exit code received so exit
      exit $respCode
   fi


# REMOVING CACHED INSTALLER
   echo "Removing Cached Installer"
   rm -R $cachedInstaller


# EXIT SUCCESS
   exit 0
