#!/bin/sh
# Configures all default user templates to enable certain settings for newly created users
#   Version: 1.0
#   Author: Ryan Powell
#   Reference: https://github.com/rypowell1988/mac-management/blob/master/macOS%20User%20Template%20Defaults
#   Note: This script uses parameter 4 in the JSS to define the Safari Home Page


# CHECK PARAMETERS HAVE BEEN PASSED
   if [[ $4 == "" ]]; then
      exit 1
   fi


# DETERMINE OS VERSION
   os_vers=$(sw_vers -productVersion)
   os_build=$(sw_vers -buildVersion)


# USER TEMPLATE DEFAULTS
   for USER_TEMPLATE in "/System/Library/User Template"/*; do
      # Disable first login prompts for Siri, iCloud, Gestures and Diagnostics
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant DidSeeSiriSetup -bool TRUE
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant DidSeeSyncSetup -bool TRUE
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant DidSeeSyncSetup2 -bool TRUE
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant DidSeeCloudSetup -bool TRUE
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant DidSeeiCloudLoginForStorageServices -bool TRUE
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant DidSeeTouchIDSetup -bool TRUE
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant GestureMovieSeen none
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.SetupAssistant LastSeenCloudProductVersion "${os_vers}"
	
      # Enable right click
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.driver.AppleHIDMouse Button2 -int 2
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.driver.AppleBluetoothMultitouch.mouse MouseButtonMode -string TwoButton
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -int 1

      # Default to search current directory
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.finder FXDefaultSearchScope -string "SCcf"

      # Avoid creating .DS_Store files on network or USB volumes
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.desktopservices DSDontWriteNetworkStores -bool true
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.desktopservices DSDontWriteUSBStores -bool true

      # Minimise into Dock App Icon
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.dock minimize-to-application -bool true

      # default Safari homepage
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.apple.Safari HomePage -string "$4"
      
      # Set Office Update Checking to Manual
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Preferences/com.microsoft.autoupdate2 HowToCheck -string "Manual"
      
      # Set Office Run on Apps to Complete
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Containers/com.microsoft.Word/Data/Library/Preferences/com.microsoft.Word kSubUIAppCompletedFirstRunSetup1507 -int 1
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Containers/com.microsoft.Excel/Data/Library/Preferences/com.microsoft.Excel kSubUIAppCompletedFirstRunSetup1507 -int 1
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Containers/com.microsoft.PowerPoint/Data/Library/Preferences/com.microsoft.PowerPoint kSubUIAppCompletedFirstRunSetup1507 -int 1
      /usr/bin/defaults write "${USER_TEMPLATE}"/Library/Containers/com.microsoft.onenote.mac/Data/Library/Preferences/com.microsoft.onenote.mac kSubUIAppCompletedFirstRunSetup1507 -int 1
      
   done


# EXIT SUCCESSFUL	
   exit 0
