#!/bin/sh
# Mounts the User Home Share and Iterates Through Top Level Directories Ensuring these are Unlocked
#   Version: 1.0
#   Author: Ryan Powell
#   Reference: https://github.com/rypowell1988/mac-management/blob/master/Mount%20User%20Home%20Share


# GET THE USER SMBHOME ATTRIBUTE
   SMBHome=$(dscl . -read "/Users/$3" SMBHome | cut -d ' ' -f2)
   if [[ $SMBHome == "" ]]; then
      # No network home, don't bother continuing
      echo "SMBHome attribute not present"
      exit 0
   fi
   echo "User home = $SMBHome"


# GET THE DOMAIN AND CHECK IF WE'RE ONLINE
   DomainName=`dsconfigad -show | awk '/Active Directory Domain/{print $NF}'`
   echo "AD Domain Name = $DomainName"
   if [[ -z $DomainName ]]; then
      echo "Cannot derive domain name via dsconfigad, exiting"
      exit 1
   fi
   echo "Testing if the network is reachable"
   ping "$DomainName" -c 4 > /dev/null 2>&1
   if [[ $? -ne 0 ]]; then
      echo "No"
      exit 0
   fi
   echo "Yes"


# SANITISE THE RETURNED SMBHOME PATH
   SMBHomeSafe=${SMBHome//\\//}


# USE APPLESCRIPT TO MOUNT THE SHARE
   echo "Mounting SMBHome"
   sudo -u $3 osascript -e "try" -e "mount volume \"smb:$SMBHomeSafe\"" -e "end try"
   if [[ ! $? -eq 0 ]]; then
      echo "Failed"
      exit "$?"
   fi
   echo "Successful"


# TEST IF THE SHARE IS MOUNTED AT /VOLIUMES/<USERNAME>
   if [[ ! -d "/Volumes/$3" ]]; then
      echo "Cannot find mounted share, exiting"
      exit 1
   fi
   
   
# LOOP THROUGH EACH ROOT DIRECTORY AND REMOVE THE UCHG FLAG
   for dir IN "/Volumes/$3/*/";
   do
      chflags nouchg "$dir"
   done
   

# EXIT SUCCESSFUL
   exit 0
